[tools]
erlang = ["28", "27"]
elixir = ["1.19", "1.18"]
go = "latest"
rebar = "latest"

[tasks.converge]
description = "Install, upgrade, and prune tools"
run = "mise install && mise upgrade && mise prune -y"
