callgraph = golang.org/x/tools/cmd/callgraph
dasel = github.com/tomwright/dasel/v2/cmd/dasel
digraph = golang.org/x/tools/cmd/digraph
doggo = github.com/mr-karan/doggo/cmd/doggo
errcheck = github.com/kisielk/errcheck
ets = github.com/zmwangx/ets
ghorg = github.com/gabrie30/ghorg
ginkgo = github.com/onsi/ginkgo/v2/ginkgo
go-mod-upgrade = github.com/oligot/go-mod-upgrade
gofumpt = mvdan.cc/gofumpt
goimports = golang.org/x/tools/cmd/goimports
golines = github.com/segmentio/golines
gomodifytags = github.com/fatih/gomodifytags
gomvp = github.com/abenz1267/gomvp
gotests = github.com/cweill/gotests/gotests
gotestsum = gotest.tools/gotestsum
govulncheck = golang.org/x/vuln/cmd/govulncheck
gup = github.com/nao1215/gup
guru = golang.org/x/tools/cmd/guru
ijq = codeberg.org/gpanders/ijq
impl = github.com/josharian/impl
jjui = github.com/idursun/jjui/cmd/jjui
jp = github.com/sgreben/jp/cmd/jp
kaf = github.com/birdayz/kaf/cmd/kaf
knoxite = github.com/knoxite/knoxite/cmd/knoxite
lux = github.com/iawia002/lux
rush = github.com/shenwei356/rush
staticcheck = honnef.co/go/tools/cmd/staticcheck
structlayout = honnef.co/go/tools/cmd/structlayout
structlayout-pretty = honnef.co/go/tools/cmd/structlayout-pretty
tailscale = tailscale.com/cmd/tailscale
termdbms = github.com/mathaou/termdbms
