ag
ast-grep
attractorr
bandwhich
bat
bottom
cargo-audit
cargo-binstall
cargo-bloat
cargo-crate
cargo-crev
cargo-criterion
cargo-deny
cargo-dist
cargo-edit
cargo-expand
cargo-feature-set
cargo-geiger
cargo-generate
cargo-machete
cargo-modules
cargo-outdated
cargo-release
cargo-show
cargo-sweep
cargo-udeps
cargo-update
cargo-vet
cargo-whatfeatures
checkmark_cli
csvlens
dirstat-rs
du-dust
dua-cli
dutree
eza
favocon
fd-find
fontfor
gbackup-rs
git-absorb
git-delta
git-hist
gitui
grex
hexyl
histo
hurl
hx
hyperfine
hysp
jj-cli
jless
just
killport
kras
lms
lsd
mise
mprocs
oha
openapi-tui
pueue
ripgrep
ripgrep_all
rnr
rtd
rustic-rs
rustscan
sccache
sd
semverator
skim
staccato
static-web-server
tidy-viewer
tokei
trippy
typos-cli
viu
wait_for
wait-for-them
xsv
ytop
zizmor
zoxide
