#! /bin/bash

plutil -convert xml1 -o "$TMPDIR/SafariBookmarks.xml" ~/Library/Safari/Bookmarks.plist
xsltproc -o ~/kod/SafariBookmarks.html ~/kod/Safari2Firebird.xslt "$TMPDIR/SafariBookmarks.xml"
rm "$TMPDIR/SafariBookmarks.xml"
